/* Single source of truth for all client-facing translations. */
const langs={
id:{home:'Beranda',inspiration:'Inspirasi',about:'Tentang kami',contact:'Hubungi kami',login:'Masuk',heroEyebrow:'JASA TIKET MURAH',heroTitle:'Pesan perjalanan, dengan cara yang lebih mudah.',heroSub:'Tiket pesawat, hotel, tur, visa, dan transfer dalam satu tempat.',flight:'Pesawat',hotel:'Hotel',tour:'Tur',visa:'Visa',from:'Dari',to:'Ke',date:'Tanggal',traveler:'Penumpang',oneAdult:'1 dewasa',twoAdults:'2 dewasa',family:'Keluarga',search:'Cari',valueTitle:'Pilihan yang relevan',valueText:'Bandingkan opsi perjalanan sesuai kebutuhan Anda.',supportTitle:'Bantuan saat dibutuhkan',supportText:'Tim kami siap membantu sebelum dan sesudah berangkat.',serviceTitle:'Satu tempat, lengkap',serviceText:'Pesawat, hotel, visa, tur, hingga transfer.',servicesEyebrow:'LAYANAN KAMI',servicesTitle:'Perjalanan Anda dimulai di sini.',inspirationLink:'Lihat inspirasi →',flightDesc:'Rute domestik dan internasional.',hotelDesc:'Tempat menginap untuk setiap perjalanan.',tourDesc:'Aktivitas pilihan di tujuan Anda.',visaDesc:'Bantuan persiapan dokumen perjalanan.',inspirationEyebrow:'INSPIRASI PERJALANAN',inspirationTitle:'Rencanakan perjalanan berikutnya.',inspirationSub:'Temukan ide singkat untuk perjalanan akhir pekan, liburan keluarga, dan petualangan lintas negara.',guideOneTitle:'Akhir pekan di Asia',guideOneText:'Pilihan kota dengan penerbangan langsung dan waktu tempuh yang nyaman.',guideTwoTitle:'Liburan keluarga',guideTwoText:'Rencanakan hotel, aktivitas, dan transfer dalam satu perjalanan.',guideThreeTitle:'Perjalanan lintas negara',guideThreeText:'Persiapkan tiket, akomodasi, dan kebutuhan visa dengan lebih teratur.',bookNow:'Mulai pencarian →',talkTeam:'Bicara dengan tim →',aboutEyebrow:'TENTANG KAMI',aboutTitle:'Perjalanan yang terencana terasa lebih ringan.',aboutSub:'Sejak 2011, JasaTiketMurah membantu pelanggan menyusun perjalanan domestik dan internasional dengan layanan yang jelas dan personal.',aboutQuote:'“Kami percaya perjalanan yang baik berawal dari pilihan yang mudah dipahami.”',founded:'Tahun layanan dimulai',categories:'Kategori kebutuhan perjalanan',partner:'Partner untuk perjalanan Anda',contactEyebrow:'HUBUNGI KAMI',contactTitle:'Bagaimana kami dapat membantu?',contactSub:'Kirim pertanyaan, saran, kritik, atau detail pesanan Anda. Tim kami akan menindaklanjuti.',fullName:'Nama lengkap',email:'Email',phone:'No. kontak',topic:'Topik',selectTopic:'Pilih topik',suggestion:'Saran',criticism:'Kritik',appreciation:'Apresiasi',orderHelp:'Bantuan pesanan',orderOptional:'Nomor pesanan (opsional)',subject:'Subjek',message:'Pesan',verification:'Verifikasi',sendMessage:'Kirim pesan',footerExplore:'Jelajahi',footerCompany:'Perusahaan',footerHelp:'Bantuan',rights:'All rights reserved.'},
en:{home:'Home',inspiration:'Inspiration',about:'About us',contact:'Contact us',login:'Sign in',heroEyebrow:'JASA TIKET MURAH',heroTitle:'Book travel, the easier way.',heroSub:'Flights, hotels, tours, visas, and transfers in one place.',flight:'Flights',hotel:'Hotels',tour:'Tours',visa:'Visa',from:'From',to:'To',date:'Dates',traveler:'Travellers',oneAdult:'1 adult',twoAdults:'2 adults',family:'Family',search:'Search',valueTitle:'Relevant choices',valueText:'Compare travel options that fit your needs.',supportTitle:'Help when you need it',supportText:'Our team is here before and after you travel.',serviceTitle:'Everything in one place',serviceText:'Flights, hotels, visas, tours, and transfers.',servicesEyebrow:'OUR SERVICES',servicesTitle:'Your journey starts here.',inspirationLink:'Explore inspiration →',flightDesc:'Domestic and international routes.',hotelDesc:'Stays for every kind of trip.',tourDesc:'Selected activities at your destination.',visaDesc:'Help preparing travel documents.',inspirationEyebrow:'TRAVEL INSPIRATION',inspirationTitle:'Plan your next journey.',inspirationSub:'Ideas for weekend breaks, family holidays, and cross-border adventures.',guideOneTitle:'A weekend in Asia',guideOneText:'Cities with direct flights and comfortable travel times.',guideTwoTitle:'Family holidays',guideTwoText:'Plan hotels, activities, and transfers in one trip.',guideThreeTitle:'Cross-border travel',guideThreeText:'Prepare tickets, stays, and visa requirements with clarity.',bookNow:'Start searching →',talkTeam:'Talk to our team →',aboutEyebrow:'ABOUT US',aboutTitle:'A well-planned journey feels lighter.',aboutSub:'Since 2011, JasaTiketMurah has helped travellers arrange domestic and international journeys with clear, personal service.',aboutQuote:'“We believe a good journey starts with choices that are easy to understand.”',founded:'Year our service began',categories:'Travel service categories',partner:'Your travel partner',contactEyebrow:'CONTACT US',contactTitle:'How can we help?',contactSub:'Send a question, suggestion, feedback, or your order details. Our team will follow up.',fullName:'Full name',email:'Email',phone:'Contact number',topic:'Topic',selectTopic:'Select a topic',suggestion:'Suggestion',criticism:'Feedback',appreciation:'Appreciation',orderHelp:'Order assistance',orderOptional:'Order number (optional)',subject:'Subject',message:'Message',verification:'Verification',sendMessage:'Send message',footerExplore:'Explore',footerCompany:'Company',footerHelp:'Help',rights:'All rights reserved.'},
th:{home:'หน้าแรก',inspiration:'แรงบันดาลใจ',about:'เกี่ยวกับเรา',contact:'ติดต่อเรา',login:'เข้าสู่ระบบ',heroTitle:'จองการเดินทางได้ง่ายขึ้น',heroSub:'เที่ยวบิน โรงแรม ทัวร์ วีซ่า และรถรับส่งในที่เดียว',flight:'เที่ยวบิน',hotel:'โรงแรม',tour:'ทัวร์',visa:'วีซ่า',from:'จาก',to:'ไปยัง',date:'วันที่',traveler:'ผู้เดินทาง',search:'ค้นหา',servicesTitle:'การเดินทางของคุณเริ่มต้นที่นี่',inspirationTitle:'วางแผนการเดินทางครั้งต่อไป',aboutTitle:'การเดินทางที่วางแผนไว้อย่างดี สบายใจกว่า',contactTitle:'เราช่วยอะไรคุณได้บ้าง?',fullName:'ชื่อเต็ม',phone:'เบอร์ติดต่อ',topic:'หัวข้อ',subject:'เรื่อง',message:'ข้อความ',sendMessage:'ส่งข้อความ',verification:'การยืนยัน'},
zh:{home:'首页',inspiration:'灵感',about:'关于我们',contact:'联系我们',login:'登录',heroTitle:'更轻松地预订旅行',heroSub:'机票、酒店、旅游、签证和接送服务一站式完成',flight:'机票',hotel:'酒店',tour:'旅游',visa:'签证',from:'出发地',to:'目的地',date:'日期',traveler:'旅客',search:'搜索',servicesTitle:'您的旅程从这里开始',inspirationTitle:'规划您的下一次旅行',aboutTitle:'精心规划的旅程更轻松',contactTitle:'我们如何帮助您？',fullName:'姓名',phone:'联系电话',topic:'主题',subject:'标题',message:'留言',sendMessage:'发送信息',verification:'验证'},
ja:{home:'ホーム',inspiration:'旅行のヒント',about:'会社概要',contact:'お問い合わせ',login:'ログイン',heroTitle:'もっと簡単に、旅を予約',heroSub:'航空券、ホテル、ツアー、ビザ、送迎を一か所で',flight:'航空券',hotel:'ホテル',tour:'ツアー',visa:'ビザ',from:'出発地',to:'目的地',date:'日付',traveler:'旅行者',search:'検索',servicesTitle:'旅はここから始まります',inspirationTitle:'次の旅を計画しましょう',aboutTitle:'よく計画された旅は、より軽やかです',contactTitle:'どのようにお手伝いできますか？',fullName:'氏名',phone:'電話番号',topic:'件名',subject:'件名',message:'メッセージ',sendMessage:'メッセージを送信',verification:'認証'},
ko:{home:'홈',inspiration:'여행 영감',about:'회사 소개',contact:'문의하기',login:'로그인',heroTitle:'더 쉽게 여행을 예약하세요',heroSub:'항공권, 호텔, 투어, 비자, 픽업 서비스를 한 곳에서',flight:'항공권',hotel:'호텔',tour:'투어',visa:'비자',from:'출발지',to:'도착지',date:'날짜',traveler:'여행객',search:'검색',servicesTitle:'여행은 여기서 시작됩니다',inspirationTitle:'다음 여행을 계획하세요',aboutTitle:'잘 계획된 여행은 더 가볍습니다',contactTitle:'어떻게 도와드릴까요?',fullName:'성명',phone:'연락처',topic:'주제',subject:'제목',message:'메시지',sendMessage:'메시지 보내기',verification:'인증'}};
const fallback=langs.id;
// Every selectable locale has a complete UI dictionary. Editorial pages fall back
// only for optional long-form copy, never for navigation, booking, or form controls.
const fullLocale=(copy)=>({...fallback,...copy});
Object.assign(langs,{
  th:fullLocale({...langs.th,login:'เข้าสู่ระบบ',valueTitle:'ตัวเลือกที่เหมาะกับคุณ',valueText:'เปรียบเทียบตัวเลือกการเดินทางที่ตรงกับความต้องการ',supportTitle:'ความช่วยเหลือเมื่อคุณต้องการ',supportText:'ทีมของเราพร้อมช่วยเหลือก่อนและหลังการเดินทาง',serviceTitle:'ครบจบในที่เดียว',serviceText:'เที่ยวบิน โรงแรม วีซ่า ทัวร์ และรถรับส่ง',inspirationLink:'ดูแรงบันดาลใจ →',footerExplore:'สำรวจ',footerCompany:'บริษัท',footerHelp:'ช่วยเหลือ',email:'อีเมล',selectTopic:'เลือกหัวข้อ',suggestion:'ข้อเสนอแนะ',criticism:'คำติชม',appreciation:'คำชื่นชม',orderHelp:'ความช่วยเหลือเกี่ยวกับการจอง',orderOptional:'หมายเลขการจอง (ไม่บังคับ)',rights:'สงวนลิขสิทธิ์'}),
  'zh-Hans':fullLocale({...langs.zh,home:'首页',inspiration:'旅行灵感',about:'关于我们',contact:'联系我们',login:'登录',valueTitle:'适合您的选择',valueText:'比较符合您需求的旅行方案。',supportTitle:'随时提供帮助',supportText:'我们的团队在出行前后为您提供协助。',serviceTitle:'一站式服务',serviceText:'机票、酒店、签证、旅游和接送。',inspirationLink:'查看灵感 →',email:'电子邮箱',selectTopic:'选择主题',suggestion:'建议',criticism:'意见反馈',appreciation:'表扬',orderHelp:'订单协助',orderOptional:'订单号（选填）',rights:'版权所有。'}),
  'zh-Hant':fullLocale({...langs.zh,home:'首頁',inspiration:'旅行靈感',about:'關於我們',contact:'聯絡我們',login:'登入',heroTitle:'更輕鬆地預訂旅程',heroSub:'機票、飯店、旅遊、簽證及接送服務一站式完成',flight:'機票',hotel:'飯店',tour:'旅遊',visa:'簽證',from:'出發地',to:'目的地',date:'日期',traveler:'旅客',search:'搜尋',valueTitle:'適合您的選擇',valueText:'比較符合您需求的旅行方案。',supportTitle:'隨時提供協助',supportText:'我們的團隊在出行前後為您提供協助。',serviceTitle:'一站式服務',serviceText:'機票、飯店、簽證、旅遊和接送。',inspirationLink:'查看靈感 →',email:'電子郵件',selectTopic:'選擇主題',suggestion:'建議',criticism:'意見回饋',appreciation:'讚賞',orderHelp:'訂單協助',orderOptional:'訂單編號（選填）',rights:'版權所有。'}),
  ja:fullLocale({...langs.ja,valueTitle:'あなたに合う選択肢',valueText:'旅のニーズに合う選択肢を比較できます。',supportTitle:'必要なときのサポート',supportText:'出発前から帰着後までチームがお手伝いします。',serviceTitle:'すべてを一か所で',serviceText:'航空券、ホテル、ビザ、ツアー、送迎。',inspirationLink:'旅行のヒントを見る →',email:'メールアドレス',selectTopic:'トピックを選択',suggestion:'ご提案',criticism:'ご意見',appreciation:'お褒めの言葉',orderHelp:'予約に関するサポート',orderOptional:'予約番号（任意）',rights:'無断転載を禁じます。'}),
  ko:fullLocale({...langs.ko,valueTitle:'나에게 맞는 선택',valueText:'여행 목적에 맞는 옵션을 비교하세요.',supportTitle:'필요할 때 도움',supportText:'여행 전후로 팀이 함께합니다.',serviceTitle:'한 곳에서 모두',serviceText:'항공권, 호텔, 비자, 투어, 픽업 서비스.',inspirationLink:'여행 영감 보기 →',email:'이메일',selectTopic:'주제 선택',suggestion:'제안',criticism:'의견',appreciation:'칭찬',orderHelp:'예약 도움',orderOptional:'예약 번호(선택)',rights:'판권 소유.'}),
  km:fullLocale({home:'ទំព័រដើម',inspiration:'គំនិតធ្វើដំណើរ',about:'អំពីយើង',contact:'ទំនាក់ទំនង',login:'ចូលគណនី',heroTitle:'កក់ដំណើររបស់អ្នកកាន់តែងាយស្រួល',heroSub:'ជើងហោះហើរ សណ្ឋាគារ ទេសចរណ៍ វីសា និងការផ្ទេរនៅកន្លែងតែមួយ',flight:'ជើងហោះហើរ',hotel:'សណ្ឋាគារ',tour:'ទេសចរណ៍',visa:'វីសា',from:'ពី',to:'ទៅ',date:'កាលបរិច្ឆេទ',traveler:'អ្នកដំណើរ',search:'ស្វែងរក',valueTitle:'ជម្រើសសម្រាប់អ្នក',valueText:'ប្រៀបធៀបជម្រើសដំណើរតាមតម្រូវការ។',supportTitle:'ជំនួយនៅពេលត្រូវការ',supportText:'ក្រុមរបស់យើងនៅជាមួយអ្នកមុន និងក្រោយដំណើរ។',serviceTitle:'គ្រប់យ៉ាងនៅកន្លែងតែមួយ',serviceText:'ជើងហោះហើរ សណ្ឋាគារ វីសា ទេសចរណ៍ និងផ្ទេរ។',inspirationLink:'មើលគំនិត →',fullName:'ឈ្មោះពេញ',email:'អ៊ីមែល',phone:'លេខទំនាក់ទំនង',topic:'ប្រធានបទ',selectTopic:'ជ្រើសប្រធានបទ',subject:'ប្រធានបទ',message:'សារ',verification:'ផ្ទៀងផ្ទាត់',sendMessage:'ផ្ញើសារ',footerExplore:'រុករក',footerCompany:'ក្រុមហ៊ុន',footerHelp:'ជំនួយ',rights:'រក្សាសិទ្ធិគ្រប់យ៉ាង។'}),
  ms:fullLocale({home:'Laman utama',inspiration:'Inspirasi',about:'Tentang kami',contact:'Hubungi kami',login:'Log masuk',heroTitle:'Tempah perjalanan dengan lebih mudah.',heroSub:'Penerbangan, hotel, lawatan, visa dan pemindahan di satu tempat.',flight:'Penerbangan',hotel:'Hotel',tour:'Lawatan',visa:'Visa',from:'Dari',to:'Ke',date:'Tarikh',traveler:'Penumpang',search:'Cari',valueTitle:'Pilihan yang relevan',valueText:'Bandingkan pilihan perjalanan mengikut keperluan anda.',supportTitle:'Bantuan apabila diperlukan',supportText:'Pasukan kami sedia membantu sebelum dan selepas perjalanan.',serviceTitle:'Lengkap dalam satu tempat',serviceText:'Penerbangan, hotel, visa, lawatan dan pemindahan.',inspirationLink:'Lihat inspirasi →',fullName:'Nama penuh',email:'E-mel',phone:'Nombor telefon',topic:'Topik',selectTopic:'Pilih topik',suggestion:'Cadangan',criticism:'Maklum balas',appreciation:'Penghargaan',orderHelp:'Bantuan tempahan',orderOptional:'Nombor tempahan (pilihan)',subject:'Subjek',message:'Mesej',verification:'Pengesahan',sendMessage:'Hantar mesej',footerExplore:'Teroka',footerCompany:'Syarikat',footerHelp:'Bantuan',rights:'Hak cipta terpelihara.'}),
  my:fullLocale({home:'ပင်မစာမျက်နှာ',inspiration:'ခရီးသွားအကြံဉာဏ်',about:'ကျွန်ုပ်တို့အကြောင်း',contact:'ဆက်သွယ်ရန်',login:'အကောင့်ဝင်ရန်',heroTitle:'ခရီးစဉ်ကို ပိုမိုလွယ်ကူစွာ ကြိုတင်မှာယူပါ',heroSub:'လေယာဉ်၊ ဟိုတယ်၊ ခရီးသွား၊ ဗီဇာနှင့် ပို့ဆောင်မှုကို တစ်နေရာတည်းတွင်',flight:'လေယာဉ်',hotel:'ဟိုတယ်',tour:'ခရီးသွား',visa:'ဗီဇာ',from:'မှ',to:'သို့',date:'ရက်စွဲ',traveler:'ခရီးသည်',search:'ရှာဖွေ',valueTitle:'သင့်အတွက် ရွေးချယ်စရာများ',valueText:'သင့်လိုအပ်ချက်နှင့်ကိုက်ညီသော ခရီးစဉ်များကို နှိုင်းယှဉ်ပါ။',supportTitle:'လိုအပ်ချိန် အကူအညီ',supportText:'ခရီးမစမီနှင့် ပြီးနောက် ကျွန်ုပ်တို့အဖွဲ့ ကူညီပေးပါမည်။',serviceTitle:'အားလုံး တစ်နေရာတည်း',serviceText:'လေယာဉ်၊ ဟိုတယ်၊ ဗီဇာ၊ ခရီးသွားနှင့် ပို့ဆောင်မှု။',inspirationLink:'အကြံဉာဏ်များ ကြည့်ရန် →',fullName:'အမည်အပြည့်အစုံ',email:'အီးမေးလ်',phone:'ဆက်သွယ်ရန်နံပါတ်',topic:'ခေါင်းစဉ်',selectTopic:'ခေါင်းစဉ်ရွေးရန်',subject:'အကြောင်းအရာ',message:'စာ',verification:'အတည်ပြုခြင်း',sendMessage:'စာပို့ရန်',footerExplore:'လေ့လာရန်',footerCompany:'ကုမ္ပဏီ',footerHelp:'အကူအညီ',rights:'မူပိုင်ခွင့်အားလုံး محفوظ။'}),
  pt:fullLocale({home:'Início',inspiration:'Inspiração',about:'Sobre nós',contact:'Contacte-nos',login:'Entrar',heroTitle:'Reserve a sua viagem com mais facilidade.',heroSub:'Voos, hotéis, passeios, vistos e traslados num só lugar.',flight:'Voos',hotel:'Hotéis',tour:'Passeios',visa:'Vistos',from:'De',to:'Para',date:'Datas',traveler:'Viajantes',search:'Pesquisar',valueTitle:'Escolhas relevantes',valueText:'Compare opções de viagem adequadas às suas necessidades.',supportTitle:'Ajuda quando precisar',supportText:'A nossa equipa ajuda antes e depois da sua viagem.',serviceTitle:'Tudo num só lugar',serviceText:'Voos, hotéis, vistos, passeios e traslados.',inspirationLink:'Ver inspiração →',fullName:'Nome completo',email:'E-mail',phone:'Contacto',topic:'Tema',selectTopic:'Selecione um tema',suggestion:'Sugestão',criticism:'Comentário',appreciation:'Elogio',orderHelp:'Ajuda com a reserva',orderOptional:'Número da reserva (opcional)',subject:'Assunto',message:'Mensagem',verification:'Verificação',sendMessage:'Enviar mensagem',footerExplore:'Explorar',footerCompany:'Empresa',footerHelp:'Ajuda',rights:'Todos os direitos reservados.'}),
  fil:fullLocale({home:'Home',inspiration:'Inspirasyon',about:'Tungkol sa amin',contact:'Makipag-ugnayan',login:'Mag-sign in',heroTitle:'Mag-book ng biyahe nang mas madali.',heroSub:'Mga flight, hotel, tour, visa, at transfer sa isang lugar.',flight:'Flight',hotel:'Hotel',tour:'Tour',visa:'Visa',from:'Mula',to:'Papunta',date:'Petsa',traveler:'Manlalakbay',search:'Maghanap',valueTitle:'Mga angkop na pagpipilian',valueText:'Ihambing ang mga opsyon para sa iyong biyahe.',supportTitle:'Tulong kapag kailangan',supportText:'Handa ang aming team bago at pagkatapos ng iyong biyahe.',serviceTitle:'Lahat sa isang lugar',serviceText:'Flight, hotel, visa, tour, at transfer.',inspirationLink:'Tingnan ang inspirasyon →',fullName:'Buong pangalan',email:'Email',phone:'Numero ng contact',topic:'Paksa',selectTopic:'Pumili ng paksa',suggestion:'Mungkahi',criticism:'Feedback',appreciation:'Pagpapahalaga',orderHelp:'Tulong sa booking',orderOptional:'Numero ng booking (opsyonal)',subject:'Subject',message:'Mensahe',verification:'Pagpapatunay',sendMessage:'Ipadala ang mensahe',footerExplore:'Galugarin',footerCompany:'Kumpanya',footerHelp:'Tulong',rights:'Lahat ng karapatan ay nakalaan.'}),
  tr:fullLocale({home:'Ana sayfa',inspiration:'İlham',about:'Hakkımızda',contact:'Bize ulaşın',login:'Giriş yap',heroTitle:'Seyahatinizi daha kolay rezerve edin.',heroSub:'Uçuşlar, oteller, turlar, vize ve transferler tek yerde.',flight:'Uçuşlar',hotel:'Oteller',tour:'Turlar',visa:'Vize',from:'Nereden',to:'Nereye',date:'Tarihler',traveler:'Yolcular',search:'Ara',valueTitle:'Size uygun seçenekler',valueText:'İhtiyaçlarınıza uygun seyahat seçeneklerini karşılaştırın.',supportTitle:'İhtiyacınız olduğunda destek',supportText:'Ekibimiz seyahatinizden önce ve sonra yanınızda.',serviceTitle:'Her şey tek yerde',serviceText:'Uçuşlar, oteller, vize, turlar ve transferler.',inspirationLink:'İlhamı keşfedin →',fullName:'Ad soyad',email:'E-posta',phone:'İletişim numarası',topic:'Konu',selectTopic:'Konu seçin',suggestion:'Öneri',criticism:'Geri bildirim',appreciation:'Takdir',orderHelp:'Rezervasyon desteği',orderOptional:'Rezervasyon numarası (isteğe bağlı)',subject:'Konu',message:'Mesaj',verification:'Doğrulama',sendMessage:'Mesaj gönder',footerExplore:'Keşfet',footerCompany:'Şirket',footerHelp:'Yardım',rights:'Tüm hakları saklıdır.'}),
  vi:fullLocale({home:'Trang chủ',inspiration:'Cảm hứng',about:'Về chúng tôi',contact:'Liên hệ',login:'Đăng nhập',heroTitle:'Đặt chuyến đi dễ dàng hơn.',heroSub:'Chuyến bay, khách sạn, tour, thị thực và đưa đón trong một nơi.',flight:'Chuyến bay',hotel:'Khách sạn',tour:'Tour',visa:'Thị thực',from:'Từ',to:'Đến',date:'Ngày đi',traveler:'Hành khách',search:'Tìm kiếm',valueTitle:'Lựa chọn phù hợp',valueText:'So sánh các lựa chọn phù hợp với nhu cầu của bạn.',supportTitle:'Hỗ trợ khi cần',supportText:'Đội ngũ của chúng tôi hỗ trợ trước và sau chuyến đi.',serviceTitle:'Tất cả trong một nơi',serviceText:'Chuyến bay, khách sạn, thị thực, tour và đưa đón.',inspirationLink:'Xem cảm hứng →',fullName:'Họ và tên',email:'Email',phone:'Số liên hệ',topic:'Chủ đề',selectTopic:'Chọn chủ đề',suggestion:'Góp ý',criticism:'Phản hồi',appreciation:'Khen ngợi',orderHelp:'Hỗ trợ đặt chỗ',orderOptional:'Mã đặt chỗ (không bắt buộc)',subject:'Tiêu đề',message:'Tin nhắn',verification:'Xác minh',sendMessage:'Gửi tin nhắn',footerExplore:'Khám phá',footerCompany:'Công ty',footerHelp:'Trợ giúp',rights:'Đã đăng ký bản quyền.'})
});
langs.zh=langs['zh-Hans'];

window.JTM_I18N={
  translations:langs,
  languageNames:{id:'Bahasa Indonesia',en:'English',km:'ខ្មែរ','zh-Hans':'简体中文','zh-Hant':'繁體中文',ja:'日本語',ko:'한국어',ms:'Bahasa Melayu',my:'မြန်မာ',pt:'Português',fil:'Tagalog',th:'ไทย',tr:'Türkçe',vi:'Tiếng Việt'},
  runtime:{
    id:{departure:'Tanggal pergi',return:'Tanggal pulang',passengers:'Penumpang',bookingClass:'Kelas pemesanan',oneWay:'Sekali jalan',roundTrip:'Pulang-pergi',multiCity:'Multi-kota',direct:'Penerbangan langsung',adult:'dewasa',child:'anak',infant:'bayi',search:'Cari'},
    en:{departure:'Departure date',return:'Return date',passengers:'Passengers',bookingClass:'Booking class',oneWay:'One way',roundTrip:'Round trip',multiCity:'Multi-city',direct:'Direct flights only',adult:'adult',child:'child',infant:'infant',search:'Search'},
    ko:{departure:'출발일',return:'귀국일',passengers:'승객',bookingClass:'좌석 등급',oneWay:'편도',roundTrip:'왕복',multiCity:'다구간',direct:'직항만',adult:'성인',child:'어린이',infant:'유아',search:'검색'},
    ja:{departure:'出発日',return:'帰国日',passengers:'旅行者',bookingClass:'搭乗クラス',oneWay:'片道',roundTrip:'往復',multiCity:'複数都市',direct:'直行便のみ',adult:'大人',child:'子供',infant:'幼児',search:'検索'},
    th:{departure:'วันเดินทาง',return:'วันกลับ',passengers:'ผู้เดินทาง',bookingClass:'ชั้นโดยสาร',oneWay:'เที่ยวเดียว',roundTrip:'ไปกลับ',multiCity:'หลายเมือง',direct:'เที่ยวบินตรงเท่านั้น',adult:'ผู้ใหญ่',child:'เด็ก',infant:'ทารก',search:'ค้นหา'},
    'zh-Hans':{departure:'出发日期',return:'返程日期',passengers:'乘客',bookingClass:'舱位等级',oneWay:'单程',roundTrip:'往返',multiCity:'多城市',direct:'仅限直飞',adult:'成人',child:'儿童',infant:'婴儿',search:'搜索'},
    'zh-Hant':{departure:'出發日期',return:'回程日期',passengers:'旅客',bookingClass:'艙等',oneWay:'單程',roundTrip:'來回',multiCity:'多城市',direct:'僅限直飛',adult:'成人',child:'兒童',infant:'嬰兒',search:'搜尋'}
  },
  t(locale,key){return this.runtime[locale]?.[key]||this.runtime.en[key]||key}
};
