if(!window.JTM_I18N){const translationLibrary=document.createElement('script');translationLibrary.src='/i18n/translations.js';translationLibrary.onload=()=>document.dispatchEvent(new Event('jtm-i18n-ready'));document.head.appendChild(translationLibrary)}
const langs={
id:{home:'Beranda',inspiration:'Inspirasi',about:'Tentang kami',contact:'Hubungi kami',login:'Masuk',heroEyebrow:'JASA TIKET MURAH',heroTitle:'Pesan perjalanan, dengan cara yang lebih mudah.',heroSub:'Tiket pesawat, hotel, tur, visa, dan transfer dalam satu tempat.',flight:'Pesawat',hotel:'Hotel',tour:'Tur',visa:'Visa',from:'Dari',to:'Ke',date:'Tanggal',traveler:'Penumpang',oneAdult:'1 dewasa',twoAdults:'2 dewasa',family:'Keluarga',search:'Cari',valueTitle:'Pilihan yang relevan',valueText:'Bandingkan opsi perjalanan sesuai kebutuhan Anda.',supportTitle:'Bantuan saat dibutuhkan',supportText:'Tim kami siap membantu sebelum dan sesudah berangkat.',serviceTitle:'Satu tempat, lengkap',serviceText:'Pesawat, hotel, visa, tur, hingga transfer.',servicesEyebrow:'LAYANAN KAMI',servicesTitle:'Perjalanan Anda dimulai di sini.',inspirationLink:'Lihat inspirasi →',flightDesc:'Rute domestik dan internasional.',hotelDesc:'Tempat menginap untuk setiap perjalanan.',tourDesc:'Aktivitas pilihan di tujuan Anda.',visaDesc:'Bantuan persiapan dokumen perjalanan.',inspirationEyebrow:'INSPIRASI PERJALANAN',inspirationTitle:'Rencanakan perjalanan berikutnya.',inspirationSub:'Temukan ide singkat untuk perjalanan akhir pekan, liburan keluarga, dan petualangan lintas negara.',guideOneTitle:'Akhir pekan di Asia',guideOneText:'Pilihan kota dengan penerbangan langsung dan waktu tempuh yang nyaman.',guideTwoTitle:'Liburan keluarga',guideTwoText:'Rencanakan hotel, aktivitas, dan transfer dalam satu perjalanan.',guideThreeTitle:'Perjalanan lintas negara',guideThreeText:'Persiapkan tiket, akomodasi, dan kebutuhan visa dengan lebih teratur.',bookNow:'Mulai pencarian →',talkTeam:'Bicara dengan tim →',aboutEyebrow:'TENTANG KAMI',aboutTitle:'Perjalanan yang terencana terasa lebih ringan.',aboutSub:'Sejak 2011, JasaTiketMurah membantu pelanggan menyusun perjalanan domestik dan internasional dengan layanan yang jelas dan personal.',aboutQuote:'“Kami percaya perjalanan yang baik berawal dari pilihan yang mudah dipahami.”',founded:'Tahun layanan dimulai',categories:'Kategori kebutuhan perjalanan',partner:'Partner untuk perjalanan Anda',contactEyebrow:'HUBUNGI KAMI',contactTitle:'Bagaimana kami dapat membantu?',contactSub:'Kirim pertanyaan, saran, kritik, atau detail pesanan Anda. Tim kami akan menindaklanjuti.',fullName:'Nama lengkap',email:'Email',phone:'No. kontak',topic:'Topik',selectTopic:'Pilih topik',suggestion:'Saran',criticism:'Kritik',appreciation:'Apresiasi',orderHelp:'Bantuan pesanan',orderOptional:'Nomor pesanan (opsional)',subject:'Subjek',message:'Pesan',verification:'Verifikasi',sendMessage:'Kirim pesan',footerExplore:'Jelajahi',footerCompany:'Perusahaan',footerHelp:'Bantuan',rights:'All rights reserved.'},
en:{home:'Home',inspiration:'Inspiration',about:'About us',contact:'Contact us',login:'Sign in',heroEyebrow:'JASA TIKET MURAH',heroTitle:'Book travel, the easier way.',heroSub:'Flights, hotels, tours, visas, and transfers in one place.',flight:'Flights',hotel:'Hotels',tour:'Tours',visa:'Visa',from:'From',to:'To',date:'Dates',traveler:'Travellers',oneAdult:'1 adult',twoAdults:'2 adults',family:'Family',search:'Search',valueTitle:'Relevant choices',valueText:'Compare travel options that fit your needs.',supportTitle:'Help when you need it',supportText:'Our team is here before and after you travel.',serviceTitle:'Everything in one place',serviceText:'Flights, hotels, visas, tours, and transfers.',servicesEyebrow:'OUR SERVICES',servicesTitle:'Your journey starts here.',inspirationLink:'Explore inspiration →',flightDesc:'Domestic and international routes.',hotelDesc:'Stays for every kind of trip.',tourDesc:'Selected activities at your destination.',visaDesc:'Help preparing travel documents.',inspirationEyebrow:'TRAVEL INSPIRATION',inspirationTitle:'Plan your next journey.',inspirationSub:'Ideas for weekend breaks, family holidays, and cross-border adventures.',guideOneTitle:'A weekend in Asia',guideOneText:'Cities with direct flights and comfortable travel times.',guideTwoTitle:'Family holidays',guideTwoText:'Plan hotels, activities, and transfers in one trip.',guideThreeTitle:'Cross-border travel',guideThreeText:'Prepare tickets, stays, and visa requirements with clarity.',bookNow:'Start searching →',talkTeam:'Talk to our team →',aboutEyebrow:'ABOUT US',aboutTitle:'A well-planned journey feels lighter.',aboutSub:'Since 2011, JasaTiketMurah has helped travellers arrange domestic and international journeys with clear, personal service.',aboutQuote:'“We believe a good journey starts with choices that are easy to understand.”',founded:'Year our service began',categories:'Travel service categories',partner:'Your travel partner',contactEyebrow:'CONTACT US',contactTitle:'How can we help?',contactSub:'Send a question, suggestion, feedback, or your order details. Our team will follow up.',fullName:'Full name',email:'Email',phone:'Contact number',topic:'Topic',selectTopic:'Select a topic',suggestion:'Suggestion',criticism:'Feedback',appreciation:'Appreciation',orderHelp:'Order assistance',orderOptional:'Order number (optional)',subject:'Subject',message:'Message',verification:'Verification',sendMessage:'Send message',footerExplore:'Explore',footerCompany:'Company',footerHelp:'Help',rights:'All rights reserved.'},
th:{home:'หน้าแรก',inspiration:'แรงบันดาลใจ',about:'เกี่ยวกับเรา',contact:'ติดต่อเรา',login:'เข้าสู่ระบบ',heroTitle:'จองการเดินทางได้ง่ายขึ้น',heroSub:'เที่ยวบิน โรงแรม ทัวร์ วีซ่า และรถรับส่งในที่เดียว',flight:'เที่ยวบิน',hotel:'โรงแรม',tour:'ทัวร์',visa:'วีซ่า',from:'จาก',to:'ไปยัง',date:'วันที่',traveler:'ผู้เดินทาง',search:'ค้นหา',servicesTitle:'การเดินทางของคุณเริ่มต้นที่นี่',inspirationTitle:'วางแผนการเดินทางครั้งต่อไป',aboutTitle:'การเดินทางที่วางแผนไว้อย่างดี สบายใจกว่า',contactTitle:'เราช่วยอะไรคุณได้บ้าง?',fullName:'ชื่อเต็ม',phone:'เบอร์ติดต่อ',topic:'หัวข้อ',subject:'เรื่อง',message:'ข้อความ',sendMessage:'ส่งข้อความ',verification:'การยืนยัน'},
zh:{home:'首页',inspiration:'灵感',about:'关于我们',contact:'联系我们',login:'登录',heroTitle:'更轻松地预订旅行',heroSub:'机票、酒店、旅游、签证和接送服务一站式完成',flight:'机票',hotel:'酒店',tour:'旅游',visa:'签证',from:'出发地',to:'目的地',date:'日期',traveler:'旅客',search:'搜索',servicesTitle:'您的旅程从这里开始',inspirationTitle:'规划您的下一次旅行',aboutTitle:'精心规划的旅程更轻松',contactTitle:'我们如何帮助您？',fullName:'姓名',phone:'联系电话',topic:'主题',subject:'标题',message:'留言',sendMessage:'发送信息',verification:'验证'},
ja:{home:'ホーム',inspiration:'旅行のヒント',about:'会社概要',contact:'お問い合わせ',login:'ログイン',heroTitle:'もっと簡単に、旅を予約',heroSub:'航空券、ホテル、ツアー、ビザ、送迎を一か所で',flight:'航空券',hotel:'ホテル',tour:'ツアー',visa:'ビザ',from:'出発地',to:'目的地',date:'日付',traveler:'旅行者',search:'検索',servicesTitle:'旅はここから始まります',inspirationTitle:'次の旅を計画しましょう',aboutTitle:'よく計画された旅は、より軽やかです',contactTitle:'どのようにお手伝いできますか？',fullName:'氏名',phone:'電話番号',topic:'件名',subject:'件名',message:'メッセージ',sendMessage:'メッセージを送信',verification:'認証'},
ko:{home:'홈',inspiration:'여행 영감',about:'회사 소개',contact:'문의하기',login:'로그인',heroTitle:'더 쉽게 여행을 예약하세요',heroSub:'항공권, 호텔, 투어, 비자, 픽업 서비스를 한 곳에서',flight:'항공권',hotel:'호텔',tour:'투어',visa:'비자',from:'출발지',to:'도착지',date:'날짜',traveler:'여행객',search:'검색',servicesTitle:'여행은 여기서 시작됩니다',inspirationTitle:'다음 여행을 계획하세요',aboutTitle:'잘 계획된 여행은 더 가볍습니다',contactTitle:'어떻게 도와드릴까요?',fullName:'성명',phone:'연락처',topic:'주제',subject:'제목',message:'메시지',sendMessage:'메시지 보내기',verification:'인증'}};
const fallback=langs.id;
// Every selectable locale has a complete UI dictionary. Editorial pages fall back
// only for optional long-form copy, never for navigation, booking, or form controls.
const fullLocale=(copy)=>({...fallback,...copy});
Object.assign(langs,{
  th:fullLocale({...langs.th,login:'เข้าสู่ระบบ',valueTitle:'ตัวเลือกที่เหมาะกับคุณ',valueText:'เปรียบเทียบตัวเลือกการเดินทางที่ตรงกับความต้องการ',supportTitle:'ความช่วยเหลือเมื่อคุณต้องการ',supportText:'ทีมของเราพร้อมช่วยเหลือก่อนและหลังการเดินทาง',serviceTitle:'ครบจบในที่เดียว',serviceText:'เที่ยวบิน โรงแรม วีซ่า ทัวร์ และรถรับส่ง',inspirationLink:'ดูแรงบันดาลใจ →',footerExplore:'สำรวจ',footerCompany:'บริษัท',footerHelp:'ช่วยเหลือ',email:'อีเมล',selectTopic:'เลือกหัวข้อ',suggestion:'ข้อเสนอแนะ',criticism:'คำติชม',appreciation:'คำชื่นชม',orderHelp:'ความช่วยเหลือเกี่ยวกับการจอง',orderOptional:'หมายเลขการจอง (ไม่บังคับ)',rights:'สงวนลิขสิทธิ์'}),
  'zh-Hans':fullLocale({...langs.zh,home:'首页',inspiration:'旅行灵感',about:'关于我们',contact:'联系我们',login:'登录',valueTitle:'适合您的选择',valueText:'比较符合您需求的旅行方案。',supportTitle:'随时提供帮助',supportText:'我们的团队在出行前后为您提供协助。',serviceTitle:'一站式服务',serviceText:'机票、酒店、签证、旅游和接送。',inspirationLink:'查看灵感 →',email:'电子邮箱',selectTopic:'选择主题',suggestion:'建议',criticism:'意见反馈',appreciation:'表扬',orderHelp:'订单协助',orderOptional:'订单号（选填）',rights:'版权所有。'}),
  'zh-Hant':fullLocale({...langs.zh,home:'首頁',inspiration:'旅行靈感',about:'關於我們',contact:'聯絡我們',login:'登入',heroTitle:'更輕鬆地預訂旅程',heroSub:'機票、飯店、旅遊、簽證及接送服務一站式完成',flight:'機票',hotel:'飯店',tour:'旅遊',visa:'簽證',from:'出發地',to:'目的地',date:'日期',traveler:'旅客',search:'搜尋',valueTitle:'適合您的選擇',valueText:'比較符合您需求的旅行方案。',supportTitle:'隨時提供協助',supportText:'我們的團隊在出行前後為您提供協助。',serviceTitle:'一站式服務',serviceText:'機票、飯店、簽證、旅遊和接送。',inspirationLink:'查看靈感 →',email:'電子郵件',selectTopic:'選擇主題',suggestion:'建議',criticism:'意見回饋',appreciation:'讚賞',orderHelp:'訂單協助',orderOptional:'訂單編號（選填）',rights:'版權所有。'}),
  ja:fullLocale({...langs.ja,valueTitle:'あなたに合う選択肢',valueText:'旅のニーズに合う選択肢を比較できます。',supportTitle:'必要なときのサポート',supportText:'出発前から帰着後までチームがお手伝いします。',serviceTitle:'すべてを一か所で',serviceText:'航空券、ホテル、ビザ、ツアー、送迎。',inspirationLink:'旅行のヒントを見る →',email:'メールアドレス',selectTopic:'トピックを選択',suggestion:'ご提案',criticism:'ご意見',appreciation:'お褒めの言葉',orderHelp:'予約に関するサポート',orderOptional:'予約番号（任意）',rights:'無断転載を禁じます。'}),
  ko:fullLocale({...langs.ko,valueTitle:'나에게 맞는 선택',valueText:'여행 목적에 맞는 옵션을 비교하세요.',supportTitle:'필요할 때 도움',supportText:'여행 전후로 팀이 함께합니다.',serviceTitle:'한 곳에서 모두',serviceText:'항공권, 호텔, 비자, 투어, 픽업 서비스.',inspirationLink:'여행 영감 보기 →',email:'이메일',selectTopic:'주제 선택',suggestion:'제안',criticism:'의견',appreciation:'칭찬',orderHelp:'예약 도움',orderOptional:'예약 번호(선택)',rights:'판권 소유.'}),
  km:fullLocale({home:'ទំព័រដើម',inspiration:'គំនិតធ្វើដំណើរ',about:'អំពីយើង',contact:'ទំនាក់ទំនង',login:'ចូលគណនី',heroTitle:'កក់ដំណើររបស់អ្នកកាន់តែងាយស្រួល',heroSub:'ជើងហោះហើរ សណ្ឋាគារ ទេសចរណ៍ វីសា និងការផ្ទេរនៅកន្លែងតែមួយ',flight:'ជើងហោះហើរ',hotel:'សណ្ឋាគារ',tour:'ទេសចរណ៍',visa:'វីសា',from:'ពី',to:'ទៅ',date:'កាលបរិច្ឆេទ',traveler:'អ្នកដំណើរ',search:'ស្វែងរក',valueTitle:'ជម្រើសសម្រាប់អ្នក',valueText:'ប្រៀបធៀបជម្រើសដំណើរតាមតម្រូវការ។',supportTitle:'ជំនួយនៅពេលត្រូវការ',supportText:'ក្រុមរបស់យើងនៅជាមួយអ្នកមុន និងក្រោយដំណើរ។',serviceTitle:'គ្រប់យ៉ាងនៅកន្លែងតែមួយ',serviceText:'ជើងហោះហើរ សណ្ឋាគារ វីសា ទេសចរណ៍ និងផ្ទេរ។',inspirationLink:'មើលគំនិត →',fullName:'ឈ្មោះពេញ',email:'អ៊ីមែល',phone:'លេខទំនាក់ទំនង',topic:'ប្រធានបទ',selectTopic:'ជ្រើសប្រធានបទ',subject:'ប្រធានបទ',message:'សារ',verification:'ផ្ទៀងផ្ទាត់',sendMessage:'ផ្ញើសារ',footerExplore:'រុករក',footerCompany:'ក្រុមហ៊ុន',footerHelp:'ជំនួយ',rights:'រក្សាសិទ្ធិគ្រប់យ៉ាង។'}),
  ms:fullLocale({home:'Laman utama',inspiration:'Inspirasi',about:'Tentang kami',contact:'Hubungi kami',login:'Log masuk',heroTitle:'Tempah perjalanan dengan lebih mudah.',heroSub:'Penerbangan, hotel, lawatan, visa dan pemindahan di satu tempat.',flight:'Penerbangan',hotel:'Hotel',tour:'Lawatan',visa:'Visa',from:'Dari',to:'Ke',date:'Tarikh',traveler:'Penumpang',search:'Cari',valueTitle:'Pilihan yang relevan',valueText:'Bandingkan pilihan perjalanan mengikut keperluan anda.',supportTitle:'Bantuan apabila diperlukan',supportText:'Pasukan kami sedia membantu sebelum dan selepas perjalanan.',serviceTitle:'Lengkap dalam satu tempat',serviceText:'Penerbangan, hotel, visa, lawatan dan pemindahan.',inspirationLink:'Lihat inspirasi →',fullName:'Nama penuh',email:'E-mel',phone:'Nombor telefon',topic:'Topik',selectTopic:'Pilih topik',suggestion:'Cadangan',criticism:'Maklum balas',appreciation:'Penghargaan',orderHelp:'Bantuan tempahan',orderOptional:'Nombor tempahan (pilihan)',subject:'Subjek',message:'Mesej',verification:'Pengesahan',sendMessage:'Hantar mesej',footerExplore:'Teroka',footerCompany:'Syarikat',footerHelp:'Bantuan',rights:'Hak cipta terpelihara.'}),
  my:fullLocale({home:'ပင်မစာမျက်နှာ',inspiration:'ခရီးသွားအကြံဉာဏ်',about:'ကျွန်ုပ်တို့အကြောင်း',contact:'ဆက်သွယ်ရန်',login:'အကောင့်ဝင်ရန်',heroTitle:'ခရီးစဉ်ကို ပိုမိုလွယ်ကူစွာ ကြိုတင်မှာယူပါ',heroSub:'လေယာဉ်၊ ဟိုတယ်၊ ခရီးသွား၊ ဗီဇာနှင့် ပို့ဆောင်မှုကို တစ်နေရာတည်းတွင်',flight:'လေယာဉ်',hotel:'ဟိုတယ်',tour:'ခရီးသွား',visa:'ဗီဇာ',from:'မှ',to:'သို့',date:'ရက်စွဲ',traveler:'ခရီးသည်',search:'ရှာဖွေ',valueTitle:'သင့်အတွက် ရွေးချယ်စရာများ',valueText:'သင့်လိုအပ်ချက်နှင့်ကိုက်ညီသော ခရီးစဉ်များကို နှိုင်းယှဉ်ပါ။',supportTitle:'လိုအပ်ချိန် အကူအညီ',supportText:'ခရီးမစမီနှင့် ပြီးနောက် ကျွန်ုပ်တို့အဖွဲ့ ကူညီပေးပါမည်။',serviceTitle:'အားလုံး တစ်နေရာတည်း',serviceText:'လေယာဉ်၊ ဟိုတယ်၊ ဗီဇာ၊ ခရီးသွားနှင့် ပို့ဆောင်မှု။',inspirationLink:'အကြံဉာဏ်များ ကြည့်ရန် →',fullName:'အမည်အပြည့်အစုံ',email:'အီးမေးလ်',phone:'ဆက်သွယ်ရန်နံပါတ်',topic:'ခေါင်းစဉ်',selectTopic:'ခေါင်းစဉ်ရွေးရန်',subject:'အကြောင်းအရာ',message:'စာ',verification:'အတည်ပြုခြင်း',sendMessage:'စာပို့ရန်',footerExplore:'လေ့လာရန်',footerCompany:'ကုမ္ပဏီ',footerHelp:'အကူအညီ',rights:'မူပိုင်ခွင့်အားလုံး محفوظ။'}),
  pt:fullLocale({home:'Início',inspiration:'Inspiração',about:'Sobre nós',contact:'Contacte-nos',login:'Entrar',heroTitle:'Reserve a sua viagem com mais facilidade.',heroSub:'Voos, hotéis, passeios, vistos e traslados num só lugar.',flight:'Voos',hotel:'Hotéis',tour:'Passeios',visa:'Vistos',from:'De',to:'Para',date:'Datas',traveler:'Viajantes',search:'Pesquisar',valueTitle:'Escolhas relevantes',valueText:'Compare opções de viagem adequadas às suas necessidades.',supportTitle:'Ajuda quando precisar',supportText:'A nossa equipa ajuda antes e depois da sua viagem.',serviceTitle:'Tudo num só lugar',serviceText:'Voos, hotéis, vistos, passeios e traslados.',inspirationLink:'Ver inspiração →',fullName:'Nome completo',email:'E-mail',phone:'Contacto',topic:'Tema',selectTopic:'Selecione um tema',suggestion:'Sugestão',criticism:'Comentário',appreciation:'Elogio',orderHelp:'Ajuda com a reserva',orderOptional:'Número da reserva (opcional)',subject:'Assunto',message:'Mensagem',verification:'Verificação',sendMessage:'Enviar mensagem',footerExplore:'Explorar',footerCompany:'Empresa',footerHelp:'Ajuda',rights:'Todos os direitos reservados.'}),
  fil:fullLocale({home:'Home',inspiration:'Inspirasyon',about:'Tungkol sa amin',contact:'Makipag-ugnayan',login:'Mag-sign in',heroTitle:'Mag-book ng biyahe nang mas madali.',heroSub:'Mga flight, hotel, tour, visa, at transfer sa isang lugar.',flight:'Flight',hotel:'Hotel',tour:'Tour',visa:'Visa',from:'Mula',to:'Papunta',date:'Petsa',traveler:'Manlalakbay',search:'Maghanap',valueTitle:'Mga angkop na pagpipilian',valueText:'Ihambing ang mga opsyon para sa iyong biyahe.',supportTitle:'Tulong kapag kailangan',supportText:'Handa ang aming team bago at pagkatapos ng iyong biyahe.',serviceTitle:'Lahat sa isang lugar',serviceText:'Flight, hotel, visa, tour, at transfer.',inspirationLink:'Tingnan ang inspirasyon →',fullName:'Buong pangalan',email:'Email',phone:'Numero ng contact',topic:'Paksa',selectTopic:'Pumili ng paksa',suggestion:'Mungkahi',criticism:'Feedback',appreciation:'Pagpapahalaga',orderHelp:'Tulong sa booking',orderOptional:'Numero ng booking (opsyonal)',subject:'Subject',message:'Mensahe',verification:'Pagpapatunay',sendMessage:'Ipadala ang mensahe',footerExplore:'Galugarin',footerCompany:'Kumpanya',footerHelp:'Tulong',rights:'Lahat ng karapatan ay nakalaan.'}),
  tr:fullLocale({home:'Ana sayfa',inspiration:'İlham',about:'Hakkımızda',contact:'Bize ulaşın',login:'Giriş yap',heroTitle:'Seyahatinizi daha kolay rezerve edin.',heroSub:'Uçuşlar, oteller, turlar, vize ve transferler tek yerde.',flight:'Uçuşlar',hotel:'Oteller',tour:'Turlar',visa:'Vize',from:'Nereden',to:'Nereye',date:'Tarihler',traveler:'Yolcular',search:'Ara',valueTitle:'Size uygun seçenekler',valueText:'İhtiyaçlarınıza uygun seyahat seçeneklerini karşılaştırın.',supportTitle:'İhtiyacınız olduğunda destek',supportText:'Ekibimiz seyahatinizden önce ve sonra yanınızda.',serviceTitle:'Her şey tek yerde',serviceText:'Uçuşlar, oteller, vize, turlar ve transferler.',inspirationLink:'İlhamı keşfedin →',fullName:'Ad soyad',email:'E-posta',phone:'İletişim numarası',topic:'Konu',selectTopic:'Konu seçin',suggestion:'Öneri',criticism:'Geri bildirim',appreciation:'Takdir',orderHelp:'Rezervasyon desteği',orderOptional:'Rezervasyon numarası (isteğe bağlı)',subject:'Konu',message:'Mesaj',verification:'Doğrulama',sendMessage:'Mesaj gönder',footerExplore:'Keşfet',footerCompany:'Şirket',footerHelp:'Yardım',rights:'Tüm hakları saklıdır.'}),
  vi:fullLocale({home:'Trang chủ',inspiration:'Cảm hứng',about:'Về chúng tôi',contact:'Liên hệ',login:'Đăng nhập',heroTitle:'Đặt chuyến đi dễ dàng hơn.',heroSub:'Chuyến bay, khách sạn, tour, thị thực và đưa đón trong một nơi.',flight:'Chuyến bay',hotel:'Khách sạn',tour:'Tour',visa:'Thị thực',from:'Từ',to:'Đến',date:'Ngày đi',traveler:'Hành khách',search:'Tìm kiếm',valueTitle:'Lựa chọn phù hợp',valueText:'So sánh các lựa chọn phù hợp với nhu cầu của bạn.',supportTitle:'Hỗ trợ khi cần',supportText:'Đội ngũ của chúng tôi hỗ trợ trước và sau chuyến đi.',serviceTitle:'Tất cả trong một nơi',serviceText:'Chuyến bay, khách sạn, thị thực, tour và đưa đón.',inspirationLink:'Xem cảm hứng →',fullName:'Họ và tên',email:'Email',phone:'Số liên hệ',topic:'Chủ đề',selectTopic:'Chọn chủ đề',suggestion:'Góp ý',criticism:'Phản hồi',appreciation:'Khen ngợi',orderHelp:'Hỗ trợ đặt chỗ',orderOptional:'Mã đặt chỗ (không bắt buộc)',subject:'Tiêu đề',message:'Tin nhắn',verification:'Xác minh',sendMessage:'Gửi tin nhắn',footerExplore:'Khám phá',footerCompany:'Công ty',footerHelp:'Trợ giúp',rights:'Đã đăng ký bản quyền.'})
});
langs.zh=langs['zh-Hans'];
let activeLang=localStorage.getItem('jtm-language')||'id';
document.querySelector('#site-header').innerHTML=`<header class="site-header"><a class="brand" href="index.html"><img src="assets/logo.png" alt="JasaTiketMurah.com"></a><button class="menu-toggle" aria-label="Menu">☰</button><nav class="main-nav"><a href="index.html" data-i18n="home">Beranda</a><a href="inspiration.html" data-i18n="inspiration">Inspirasi</a><a href="about.html" data-i18n="about">Tentang kami</a><a href="contact.html" data-i18n="contact">Hubungi kami</a></nav><div class="header-right"><select id="language" class="language-select" aria-label="Language"><option value="id">🇮🇩 Indonesia</option><option value="en">🇬🇧 English</option><option value="th">🇹🇭 ไทย</option><option value="zh">🇨🇳 中文</option><option value="ja">🇯🇵 日本語</option><option value="ko">🇰🇷 한국어</option></select><button class="account-button" data-i18n="login">Masuk</button></div></header>`;
document.querySelector('#site-footer').innerHTML=`<footer><div class="wrap footer-grid"><div><img class="footer-logo" src="assets/logo.png" alt="JasaTiketMurah.com"><p>Flight · Hotel · Tour · Visa · Transfer</p></div><div><h3 data-i18n="footerExplore">Jelajahi</h3><a href="index.html#booking" data-i18n="flight">Pesawat</a><a href="index.html#booking" data-i18n="hotel">Hotel</a><a href="index.html#booking" data-i18n="tour">Tur</a><a href="index.html#booking" data-i18n="visa">Visa</a></div><div><h3 data-i18n="footerCompany">Perusahaan</h3><a href="about.html" data-i18n="about">Tentang kami</a><a href="contact.html" data-i18n="contact">Hubungi kami</a><a href="#">Syarat & ketentuan</a><a href="#">Kebijakan privasi</a></div><div><h3 data-i18n="footerHelp">Bantuan</h3><a href="mailto:cs@jasatiketmurah.com">cs@jasatiketmurah.com</a><a href="contact.html">Pusat bantuan</a></div></div><div class="wrap copyright">Copyright © 2011-<span id="year"></span> JasaTiketMurah.com by PT Shiro Xpress International. <span data-i18n="rights">All rights reserved.</span></div></footer>`;
function translate(){const dict={...fallback,...langs[activeLang]};document.documentElement.lang=activeLang;document.querySelectorAll('[data-i18n]').forEach(el=>{const text=dict[el.dataset.i18n];if(text)el.textContent=text});document.querySelector('#language').value=activeLang;document.title=document.title.replace(/^.*? \| /,'')+' | JasaTiketMurah';}
translate();document.querySelector('#year').textContent=new Date().getFullYear();document.querySelector('#language').addEventListener('change',e=>{activeLang=e.target.value;localStorage.setItem('jtm-language',activeLang);translate()});document.querySelector('.menu-toggle').addEventListener('click',()=>document.querySelector('.main-nav').classList.toggle('open'));
const dateField=document.querySelector('#travel-date');if(dateField){dateField.min=new Date().toISOString().split('T')[0];dateField.value=new Date(Date.now()+12096e5).toISOString().split('T')[0];const presets={flight:['Jakarta (CGK)','Pilih kota tujuan'],hotel:['','Contoh: Ubud, Bali'],tour:['','Contoh: Tokyo city tour'],visa:['Indonesia','Contoh: Jepang']};document.querySelectorAll('.service-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.service-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');const p=presets[tab.dataset.service];document.querySelector('#origin').value=p[0];document.querySelector('#destination').value='';document.querySelector('#destination').placeholder=p[1]}));document.querySelector('.swap').addEventListener('click',()=>{const a=document.querySelector('#origin'),b=document.querySelector('#destination');[a.value,b.value]=[b.value,a.value]});document.querySelector('#search-form').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#search-feedback').textContent='Pencarian Anda siap. Harga live akan tersedia setelah integrasi API.'})}
let answer;function captcha(){const a=Math.floor(Math.random()*90)+10,b=Math.floor(Math.random()*(a+1));answer=a-b;const label=document.querySelector('#captcha-label');if(label)label.firstChild.textContent=`${(langs[activeLang]||fallback).verification||fallback.verification}: ${a} − ${b} = `}captcha();document.querySelector('#contact-form')?.addEventListener('submit',e=>{e.preventDefault();const f=document.querySelector('#contact-feedback');if(Number(document.querySelector('#captcha').value)!==answer){f.textContent='Jawaban verifikasi belum tepat.';captcha();return}f.textContent='Terima kasih. Pesan Anda siap dikirim ke tim kami.';e.currentTarget.reset();captcha()});

const routeLinks=['/','/inspiration/','/about/','/contact/'];document.querySelectorAll('#site-header .main-nav a').forEach((link,index)=>link.href=routeLinks[index]);document.querySelectorAll('img[src="assets/logo.png"]').forEach(image=>image.src='/assets/logo.png');const legalLinks=document.querySelectorAll('#site-footer a[href="#"]');if(legalLinks[0])legalLinks[0].href='/terms/';if(legalLinks[1])legalLinks[1].href='/privacy/';
const aboutCopy={id:'<p>Jasa Tiket Murah hadir untuk membantu pelanggan menyusun perjalanan dengan lebih tenang. Kami memahami bahwa setiap perjalanan memiliki kebutuhan yang berbeda: perjalanan bisnis yang terjadwal, liburan keluarga, kunjungan singkat, hingga perjalanan internasional yang memerlukan persiapan visa.</p><p>Layanan kami mencakup pencarian tiket pesawat, hotel, tur dan aktivitas, pengurusan visa, serta transfer. Kami berfokus pada informasi yang jelas, pilihan yang relevan, dan bantuan yang mudah dijangkau saat pelanggan memerlukannya.</p><p>Di balik setiap pesanan, Jasa Tiket Murah ingin menjadi partner yang dapat diandalkan—dari tahap perencanaan hingga perjalanan selesai.</p>',en:'<p>Jasa Tiket Murah helps travellers plan with greater confidence. Every trip has different needs: a scheduled business journey, a family holiday, a short visit, or an international itinerary that requires visa preparation.</p><p>Our services cover flights, hotels, tours and activities, visa assistance, and transfers. We focus on clear information, relevant options, and accessible support when travellers need it.</p><p>Behind every booking, Jasa Tiket Murah aims to be a dependable partner from planning through the end of your journey.</p>',th:'<p>Jasa Tiket Murah ช่วยให้ผู้เดินทางวางแผนได้อย่างมั่นใจยิ่งขึ้น เราให้บริการเที่ยวบิน โรงแรม ทัวร์ วีซ่า และรถรับส่ง พร้อมข้อมูลที่ชัดเจนและการสนับสนุนที่เข้าถึงได้</p>',zh:'<p>Jasa Tiket Murah 协助旅客更安心地规划行程。我们提供机票、酒店、旅游活动、签证协助和接送服务，并提供清晰的信息与支持。</p>',ja:'<p>Jasa Tiket Murah は、お客様が安心して旅を計画できるよう支援します。航空券、ホテル、ツアー、ビザ、送迎をわかりやすい情報とともにご案内します。</p>',ko:'<p>Jasa Tiket Murah는 고객이 더 안심하고 여행을 계획하도록 돕습니다. 항공권, 호텔, 투어, 비자, 픽업 서비스를 명확한 정보와 함께 제공합니다.</p>'};document.querySelector('#about-copy')?.insertAdjacentHTML('beforeend',aboutCopy[activeLang]||aboutCopy.id);
['about','contact'].forEach(name=>document.querySelectorAll(`a[href="${name}.html"]`).forEach(link=>link.href=`/${name}/`));Object.values(langs).forEach(dict=>['heroEyebrow','inspirationEyebrow','aboutEyebrow','contactEyebrow'].forEach(key=>delete dict[key]));langs.id.aboutSub='Sejak 2011, Jasa Tiket Murah membantu pelanggan menyusun perjalanan domestik dan internasional dengan layanan yang jelas dan personal.';langs.en.aboutSub='Since 2011, Jasa Tiket Murah has helped travellers arrange domestic and international journeys with clear, personal service.';translate();
document.querySelector('#language').addEventListener('change',()=>{const target=document.querySelector('#about-copy');if(target)target.innerHTML=aboutCopy[activeLang]||aboutCopy.id});

// Flight booking flow: trip type, traveller allocation (maximum seven), and date rules.
const bookingForm=document.querySelector('#search-form');
if(bookingForm){
  const tabs=document.createElement('div');tabs.className='trip-types';tabs.innerHTML='<label><input type="radio" name="trip-type" value="one-way" checked> Sekali jalan</label><label><input type="radio" name="trip-type" value="round-trip"> Pulang-pergi</label><label><input type="radio" name="trip-type" value="multi-city"> Multi-kota</label>';
  document.querySelector('.search-card').insertBefore(tabs,bookingForm);tabs.insertAdjacentHTML('beforeend','<label class="direct-choice"><input type="checkbox" name="direct-only"> <span data-runtime="direct">Penerbangan langsung</span></label>');
  const travellerLabel=bookingForm.querySelectorAll('label')[3];
  travellerLabel.innerHTML='<small>Penumpang</small><button type="button" class="traveller-trigger" aria-expanded="false">1 dewasa</button><div class="traveller-popover" hidden><div class="traveller-row"><span><b>Dewasa</b><small>12 tahun ke atas</small></span><div class="counter"><button type="button" data-counter="adults" data-step="-1">−</button><output data-count="adults">1</output><button type="button" data-counter="adults" data-step="1">+</button></div></div><div class="traveller-row"><span><b>Anak</b><small>2–11 tahun</small></span><div class="counter"><button type="button" data-counter="children" data-step="-1">−</button><output data-count="children">0</output><button type="button" data-counter="children" data-step="1">+</button></div></div><div class="traveller-row"><span><b>Bayi</b><small>Di bawah 2 tahun</small></span><div class="counter"><button type="button" data-counter="infants" data-step="-1">−</button><output data-count="infants">0</output><button type="button" data-counter="infants" data-step="1">+</button></div></div><p class="traveller-note">Maksimal 7 penumpang per pemesanan.</p><button type="button" class="traveller-done">Selesai</button></div>';
  const state={adults:1,children:0,infants:0};const trigger=travellerLabel.querySelector('.traveller-trigger');const popover=travellerLabel.querySelector('.traveller-popover');
  const refreshTravellers=()=>{Object.entries(state).forEach(([key,value])=>travellerLabel.querySelector(`[data-count="${key}"]`).textContent=value);const pieces=[];if(state.adults)pieces.push(`${state.adults} dewasa`);if(state.children)pieces.push(`${state.children} anak`);if(state.infants)pieces.push(`${state.infants} bayi`);trigger.textContent=pieces.join(', ');travellerLabel.querySelectorAll('.counter button[data-step="1"]').forEach(button=>button.disabled=state.adults+state.children+state.infants>=7);travellerLabel.querySelector('[data-counter="adults"][data-step="-1"]').disabled=state.adults<=1;['children','infants'].forEach(key=>travellerLabel.querySelector(`[data-counter="${key}"][data-step="-1"]`).disabled=state[key]===0)};
  trigger.addEventListener('click',()=>{popover.hidden=!popover.hidden;trigger.setAttribute('aria-expanded',String(!popover.hidden))});travellerLabel.querySelector('.traveller-done').addEventListener('click',()=>{popover.hidden=true;trigger.setAttribute('aria-expanded','false')});travellerLabel.querySelectorAll('[data-counter]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.counter;const next=state[key]+Number(button.dataset.step);if(next>=0&&state.adults+state.children+state.infants+Number(button.dataset.step)<=7&&(key!=='adults'||next>=1)){state[key]=next;refreshTravellers()}}));refreshTravellers();
  const departure=document.querySelector('#travel-date');const returnField=document.createElement('label');returnField.className='return-date';returnField.hidden=true;returnField.innerHTML='<small>Tanggal pulang</small><input id="return-date" type="date">';departure.parentElement.after(returnField);const returnDate=returnField.querySelector('input');
  const syncReturn=()=>{returnDate.min=departure.value||new Date().toISOString().slice(0,10);if(returnDate.value&&returnDate.value<returnDate.min)returnDate.value=returnDate.min};departure.addEventListener('change',syncReturn);syncReturn();
  tabs.addEventListener('change',event=>{if(event.target.name!=='trip-type')return;if(event.target.value==='multi-city'){window.location.href='/multi-city/';return}returnField.hidden=event.target.value!=='round-trip';returnDate.required=event.target.value==='round-trip';if(!returnDate.value)returnDate.value=returnDate.min});
  bookingForm.addEventListener('submit',event=>{if(returnField.hidden===false&&returnDate.value<departure.value){event.preventDefault();document.querySelector('#search-feedback').textContent='Tanggal pulang tidak boleh lebih awal dari tanggal berangkat.'}});
}

document.head.insertAdjacentHTML('beforeend','<style>.trip-types{display:flex;gap:18px;padding:16px 0 4px;font-size:.88rem;font-weight:600;color:#334155}.trip-types label{display:flex;align-items:center;gap:6px;cursor:pointer}.trip-types input{accent-color:#1e3a8a}.traveller-trigger{height:48px;text-align:left;border:1px solid #cbd5e1;border-radius:5px;background:#fff;padding:10px;color:#0d1b2a;font:500 .91rem DM Sans;cursor:pointer}.traveller-popover{position:absolute;z-index:8;top:76px;right:0;width:320px;padding:14px;background:#fff;border:1px solid #cbd5e1;border-radius:8px;box-shadow:0 16px 35px rgba(13,27,42,.18)}.search-form label{position:relative}.traveller-row{display:flex;justify-content:space-between;align-items:center;padding:10px 0;border-bottom:1px solid #e2e8f0}.traveller-row span{display:grid}.traveller-row small{font-weight:400;color:#64748b}.counter{display:flex;align-items:center;gap:11px}.counter button{width:28px;height:28px;border:1px solid #cbd5e1;background:#fff;border-radius:50%;font-size:18px;color:#1e3a8a;cursor:pointer}.counter button:disabled{opacity:.35;cursor:not-allowed}.counter output{min-width:14px;text-align:center}.traveller-note{font-size:.76rem;color:#64748b;margin:11px 0}.traveller-done{width:100%;border:0;background:#1e3a8a;color:#fff;border-radius:4px;padding:9px;font-weight:700;cursor:pointer}@media(max-width:560px){.trip-types{gap:12px;overflow:auto;white-space:nowrap}.traveller-popover{position:fixed;inset:auto 16px 16px;width:auto}.return-date{display:block!important}}</style>');

// Guard the booking controls against mobile CSS overrides and enforce the 300-day window.
document.head.insertAdjacentHTML('beforeend','<style>.return-date[hidden],.traveller-popover[hidden]{display:none!important}.currency-select{border:0;background:transparent;font:600 .84rem DM Sans;color:#334155;padding:8px;max-width:170px}@media(max-width:700px){.currency-select{display:none}}</style>');
const today=new Date();const maxTravelDate=new Date(today);maxTravelDate.setDate(today.getDate()+300);const limit300=maxTravelDate.toISOString().slice(0,10);document.querySelectorAll('#travel-date,#return-date').forEach(field=>{field.min=today.toISOString().slice(0,10);field.max=limit300});
const languageSelect=document.querySelector('#language');if(languageSelect){languageSelect.innerHTML='<option value="id">🇮🇩 Indonesia</option><option value="en">🇬🇧 English</option><option value="km">🇰🇭 Khmer</option><option value="zh-Hans">🇨🇳 Chinese, Simplified</option><option value="zh-Hant">🇹🇼 Chinese, Traditional</option><option value="ja">🇯🇵 Japanese</option><option value="ko">🇰🇷 Korean</option><option value="ms">🇲🇾 Malay</option><option value="my">🇲🇲 Myanmar</option><option value="pt">🇵🇹 Portuguese</option><option value="fil">🇵🇭 Tagalog</option><option value="th">🇹🇭 Thai</option><option value="tr">🇹🇷 Turkish</option><option value="vi">🇻🇳 Vietnamese</option>';languageSelect.value=activeLang;languageSelect.insertAdjacentHTML('afterend','<select id="currency" class="currency-select" aria-label="Mata uang"><option value="IDR">IDR — Indonesia Rupiah</option><option value="AUD">AUD — Australian Dollar</option><option value="CAD">CAD — Canadian Dollar</option><option value="CNY">CNY — Chinese Yuan</option><option value="GBP">GBP — British Pound</option><option value="JPY">JPY — Japanese Yen</option><option value="KRW">KRW — South Korean Won</option><option value="MYR">MYR — Malaysian Ringgit</option><option value="NZD">NZD — New Zealand Dollar</option><option value="PHP">PHP — Philippine Peso</option><option value="SGD">SGD — Singapore Dollar</option><option value="USD">USD — United States Dollar</option><option value="VND">VND — Vietnamese Dong</option></select>');const currency=document.querySelector('#currency');currency.value=localStorage.getItem('jtm-currency')||'IDR';currency.addEventListener('change',()=>localStorage.setItem('jtm-currency',currency.value))}
document.querySelector('[data-service="tour"]')?.firstChild.replaceWith('🧭 ');document.querySelector('[data-service="visa"]')?.firstChild.replaceWith('🛂 ');document.querySelectorAll('.service-tile').forEach(tile=>{if(tile.querySelector('[data-i18n="tour"]'))tile.firstChild.replaceWith('🧭');if(tile.querySelector('[data-i18n="visa"]'))tile.firstChild.replaceWith('🛂')});

// Search state is deliberately session-only: it disappears when the tab/window closes.
// Live supplier data is fetched only after the server-side API gateway is connected.
document.head.insertAdjacentHTML('beforeend','<style>.booking-hero{background:linear-gradient(90deg,rgba(13,27,42,.94) 0%,rgba(13,27,42,.78) 46%,rgba(13,27,42,.30) 100%),url("/assets/hero-booking.png") center/cover no-repeat}.booking-hero h1{color:#fff;max-width:680px}.booking-hero .hero-sub{color:#eaf5fb;max-width:600px}.search-card{box-shadow:0 18px 42px rgba(13,27,42,.22)}@media(max-width:700px){.booking-hero{background-position:60% center}}</style>');
const searchForm=document.querySelector('#search-form');let idleSearchTimer;
const clearSearchSession=()=>{sessionStorage.removeItem('jtm-last-search');sessionStorage.removeItem('jtm-search-results');const notice=document.querySelector('#search-feedback');if(notice&&notice.dataset.searchState==='stored'){notice.textContent='Sesi pencarian berakhir. Cari lagi untuk mendapatkan data terbaru dari API.';notice.dataset.searchState='expired'}};
const resetSearchIdleTimer=()=>{clearTimeout(idleSearchTimer);idleSearchTimer=setTimeout(clearSearchSession,30000)};
if(searchForm){searchForm.querySelectorAll('input,select,button').forEach(control=>['input','change','focus','click'].forEach(eventName=>control.addEventListener(eventName,resetSearchIdleTimer)));searchForm.addEventListener('submit',()=>{sessionStorage.setItem('jtm-last-search',JSON.stringify({origin:document.querySelector('#origin')?.value||'',destination:document.querySelector('#destination')?.value||'',travelDate:document.querySelector('#travel-date')?.value||'',savedAt:Date.now()}));const notice=document.querySelector('#search-feedback');if(notice)notice.dataset.searchState='stored';resetSearchIdleTimer()});resetSearchIdleTimer()}
window.addEventListener('pagehide',clearSearchSession);

// Local airport catalogue for the first search experience. The production gateway
// will replace this with its supplier-backed airport index.
const airportCatalogue=[
  {code:'CGK',city:'Jakarta',name:'Soekarno-Hatta International Airport'},
  {code:'HLP',city:'Jakarta',name:'Halim Perdanakusuma International Airport'},
  {code:'DPS',city:'Denpasar',name:'I Gusti Ngurah Rai International Airport'},
  {code:'SUB',city:'Surabaya',name:'Juanda International Airport'},
  {code:'KNO',city:'Medan',name:'Kualanamu International Airport'},
  {code:'YIA',city:'Yogyakarta',name:'Yogyakarta International Airport'},
  {code:'SIN',city:'Singapore',name:'Singapore Changi Airport'},
  {code:'KUL',city:'Kuala Lumpur',name:'Kuala Lumpur International Airport'},
  {code:'BKK',city:'Bangkok',name:'Suvarnabhumi Airport'},
  {code:'NRT',city:'Tokyo',name:'Narita International Airport'},
  {code:'ICN',city:'Seoul',name:'Incheon International Airport'},
  {code:'SYD',city:'Sydney',name:'Sydney Kingsford Smith Airport'}
];
const airportValue=airport=>`${airport.city} (${airport.code})`;
const airportMatch=value=>airportCatalogue.find(airport=>airportValue(airport).toLowerCase()===value.trim().toLowerCase());
if(searchForm){
  [document.querySelector('#origin'),document.querySelector('#destination')].forEach(input=>{
    if(!input)return;input.setAttribute('autocomplete','off');const list=document.createElement('div');list.className='airport-suggestions';list.hidden=true;input.parentElement.appendChild(list);
    const render=()=>{const term=input.value.trim().toLowerCase();const matches=airportCatalogue.filter(airport=>`${airport.code} ${airport.city} ${airport.name}`.toLowerCase().includes(term)).slice(0,6);list.innerHTML=matches.map(airport=>`<button type="button" data-airport="${airport.code}"><b>${airport.city} (${airport.code})</b><small>${airport.name}</small></button>`).join('');list.hidden=!matches.length};
    input.addEventListener('input',render);input.addEventListener('focus',render);input.addEventListener('blur',()=>setTimeout(()=>list.hidden=true,140));list.addEventListener('click',event=>{const button=event.target.closest('[data-airport]');if(!button)return;const airport=airportCatalogue.find(item=>item.code===button.dataset.airport);input.value=airportValue(airport);list.hidden=true;input.dispatchEvent(new Event('change',{bubbles:true}))});
  });
  searchForm.addEventListener('submit',event=>{const origin=airportMatch(document.querySelector('#origin')?.value||'');const destination=airportMatch(document.querySelector('#destination')?.value||'');const feedback=document.querySelector('#search-feedback');if(!origin||!destination){event.preventDefault();feedback.textContent='Pilih bandara dari daftar saran agar rute dapat divalidasi.';return}if(origin.code===destination.code){event.preventDefault();feedback.textContent='Bandara keberangkatan dan tujuan harus berbeda.';return}event.preventDefault();const query=new URLSearchParams({from:origin.code,to:destination.code,date:document.querySelector('#travel-date')?.value||''});window.location.href=`/results/?${query.toString()}`});
}
const resultRoot=document.querySelector('#flight-results');
if(resultRoot){
  const query=new URLSearchParams(location.search);const from=query.get('from')||'CGK',to=query.get('to')||'DPS';const samples=[{airline:'Garuda Indonesia',code:'GA',time:'07:10 – 10:05',duration:'1j 55m',stops:0,price:1425000},{airline:'Batik Air',code:'ID',time:'09:20 – 12:15',duration:'1j 55m',stops:0,price:1189000},{airline:'Singapore Airlines',code:'SQ',time:'12:15 – 20:10',duration:'6j 55m',stops:1,price:2099000}];
  const renderResults=()=>{const direct=document.querySelector('#filter-direct')?.checked;const ordered=[...samples].filter(item=>!direct||item.stops===0).sort((a,b)=>document.querySelector('#sort-results')?.value==='price-desc'?b.price-a.price:a.price-b.price);resultRoot.innerHTML=ordered.map(item=>`<article class="flight-result"><div><b>${item.airline}</b><small>${item.code} · Economy</small></div><div><b>${item.time}</b><small>${from} → ${to} · ${item.duration}</small></div><div><small>${item.stops===0?'Langsung':'1 transit'}</small></div><div class="result-price"><b>Rp${item.price.toLocaleString('id-ID')}</b><button type="button">Pilih</button></div></article>`).join('')||'<p>Tidak ada penerbangan yang cocok dengan filter Anda.</p>'};
  document.querySelector('#result-route').textContent=`${from} ke ${to}`;document.querySelectorAll('#filter-direct,#sort-results').forEach(control=>control.addEventListener('change',renderResults));renderResults();
}

document.head.insertAdjacentHTML('beforeend','<style>.booking-hero{background:linear-gradient(180deg,rgba(13,27,42,.72) 0%,rgba(13,27,42,.10) 28%,rgba(13,27,42,.10) 68%,rgba(13,27,42,.70) 100%),linear-gradient(90deg,rgba(13,27,42,.86),rgba(13,27,42,.28)),url("/assets/hero-booking.png") center/cover no-repeat}.booking-hero .search-form{grid-template-columns:1.15fr 38px 1.15fr 1fr .9fr .9fr}.booking-hero .search-form .primary-button{grid-column:1/-1;justify-self:end;min-width:170px;margin-top:8px}.booking-extras{display:flex;gap:12px;align-items:center;margin-top:14px}.group-booking-link{color:#fff;background:rgba(255,255,255,.15);border:1px solid rgba(255,255,255,.55);border-radius:5px;padding:10px 14px;font-size:.86rem;font-weight:700;text-decoration:none}.charter-tab{color:#0d1b2a!important}@media(max-width:1000px){.booking-hero .search-form{grid-template-columns:1fr 36px 1fr 1fr}.booking-hero .search-form .primary-button{grid-column:1/-1}}@media(max-width:700px){.booking-extras{align-items:stretch}.group-booking-link{text-align:center}.booking-hero .search-form{grid-template-columns:1fr}.booking-hero .search-form .primary-button{justify-self:stretch}.site-header{padding-inline:16px}.brand img{width:158px}.booking-hero h1{font-size:clamp(2rem,10vw,3rem)}.service-tab{font-size:.82rem}}@media(max-width:390px){.brand img{width:138px}.wrap{width:calc(100% - 24px)}.search-card{padding-inline:12px}}</style>');
document.querySelector('.brand')?.setAttribute('href','/');document.querySelector('[data-service="hotel"]')?.firstChild.replaceWith('🛏️ ');document.querySelectorAll('.service-tile').forEach(tile=>{if(tile.querySelector('[data-i18n="hotel"]'))tile.firstChild.replaceWith('🛏️')});
const polishLanguage=document.querySelector('#language');if(polishLanguage){polishLanguage.innerHTML='<option value="id">🇮🇩 Bahasa Indonesia</option><option value="en">🇬🇧 English</option><option value="km">🇰🇭 ខ្មែរ</option><option value="zh-Hans">🇨🇳 简体中文</option><option value="zh-Hant">🇹🇼 繁體中文</option><option value="ja">🇯🇵 日本語</option><option value="ko">🇰🇷 한국어</option><option value="ms">🇲🇾 Bahasa Melayu</option><option value="my">🇲🇲 မြန်မာ</option><option value="pt">🇵🇹 Português</option><option value="fil">🇵🇭 Tagalog</option><option value="th">🇹🇭 ไทย</option><option value="tr">🇹🇷 Türkçe</option><option value="vi">🇻🇳 Tiếng Việt</option>';polishLanguage.value=activeLang}document.querySelector('#currency')?.replaceChildren(...['IDR','AUD','CAD','CNY','GBP','JPY','KRW','MYR','NZD','PHP','SGD','USD','VND'].map(code=>new Option(code,code)));
if(bookingForm){const serviceTabs=document.querySelector('.service-tabs');if(serviceTabs&&!serviceTabs.querySelector('[data-service="charter"]'))serviceTabs.insertAdjacentHTML('beforeend','<a class="service-tab charter-tab" data-service="charter" href="/charter/">🛩️ <b>Private Jet Charter</b></a>');const searchButton=bookingForm.querySelector('.primary-button');if(searchButton&&!bookingForm.querySelector('#booking-class'))searchButton.insertAdjacentHTML('beforebegin','<label><small data-runtime="bookingClass">Kelas pemesanan</small><select id="booking-class" name="booking-class"><option>Ekonomi</option><option>Ekonomi Premium</option><option>Bisnis</option><option>Kelas Utama / Suites</option></select></label>');if(!document.querySelector('.group-booking-link'))bookingForm.insertAdjacentHTML('afterend','<div class="booking-extras"><a class="group-booking-link" href="/group-booking/">Ingin melakukan group booking lebih dari 10 orang? Bisa. Yuk klik di sini</a></div>')}
const groupForm=document.querySelector('#group-booking-form');if(groupForm){let groupAnswer;const groupCaptcha=()=>{const first=Math.floor(Math.random()*90)+10,second=Math.floor(Math.random()*(first+1));groupAnswer=first-second;document.querySelector('#group-captcha-label').textContent=`Verifikasi: ${first} − ${second} = `};groupCaptcha();groupForm.addEventListener('submit',async event=>{event.preventDefault();const feedback=document.querySelector('#group-booking-feedback');if(Number(document.querySelector('#group-captcha').value)!==groupAnswer){feedback.textContent='Jawaban verifikasi belum tepat.';groupCaptcha();return}const payload=Object.fromEntries(new FormData(groupForm));feedback.textContent='Mengirim permintaan Anda…';try{const response=await fetch('/api/group-booking.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error();feedback.textContent='Permintaan terkirim. Salinan email telah dikirim ke alamat Anda.';groupForm.reset()}catch{sessionStorage.setItem('jtm-group-booking',JSON.stringify(payload));feedback.textContent='Permintaan tersimpan. Layanan email sedang tidak tersedia; tim kami akan menindaklanjuti.'}groupCaptcha()})}

// Checkout is intentionally client-side until payment and account services are connected.
const generateOrderNumber=(type='F')=>`JTM${type}${Math.floor(Date.now()/1000)}`;
document.querySelector('#flight-results')?.addEventListener('click',event=>{const button=event.target.closest('.result-price button');if(!button)return;const card=button.closest('.flight-result');const price=card.querySelector('.result-price b')?.textContent||'';const airline=card.querySelector('b')?.textContent||'';window.location.href=`/checkout/?airline=${encodeURIComponent(airline)}&price=${encodeURIComponent(price)}&route=${encodeURIComponent(document.querySelector('#result-route')?.textContent||'')}`});
const checkoutForm=document.querySelector('#checkout-form');if(checkoutForm){const query=new URLSearchParams(location.search);document.querySelector('#checkout-route').textContent=query.get('route')||'CGK → DPS';document.querySelector('#checkout-airline').textContent=query.get('airline')||'Batik Air';document.querySelector('#checkout-total').textContent=query.get('price')||'Rp1.189.000';document.querySelector('#checkout-date').textContent=new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'}).format(new Date());checkoutForm.querySelectorAll('[name="bookingMode"]').forEach(input=>input.addEventListener('change',()=>{const member=input.value==='member'&&input.checked;const password=checkoutForm.querySelector('.member-password');password.hidden=!member;password.querySelector('input').required=member}));checkoutForm.addEventListener('submit',event=>{event.preventDefault();const orderNumber=generateOrderNumber('F');sessionStorage.setItem('jtm-order',JSON.stringify({number:orderNumber,customer:Object.fromEntries(new FormData(checkoutForm)),route:query.get('route'),price:query.get('price')}));window.location.href=`/order-confirmation/?order=${orderNumber}`})}
const confirmation=document.querySelector('#order-number');if(confirmation){const order=new URLSearchParams(location.search).get('order')||JSON.parse(sessionStorage.getItem('jtm-order')||'{}').number||generateOrderNumber('F');confirmation.textContent=order;const detail=JSON.parse(sessionStorage.getItem('jtm-order')||'{}');if(detail.customer?.email)document.querySelector('#order-confirmation-detail').textContent=`Ringkasan pesanan dikirim ke ${detail.customer.email}.`}

const runtimeCopy=()=>window.JTM_I18N?.runtime?.[activeLang]||window.JTM_I18N?.runtime?.en||{departure:'Departure date',return:'Return date',passengers:'Passengers',bookingClass:'Booking class',oneWay:'One way',roundTrip:'Round trip',multiCity:'Multi-city',direct:'Direct flights only',adult:'adult',child:'child',infant:'infant'};
const refreshDynamicLocale=()=>{const copy=runtimeCopy();document.querySelector('#travel-date')?.previousElementSibling&&(document.querySelector('#travel-date').previousElementSibling.textContent=copy.departure);document.querySelector('#return-date')?.parentElement.querySelector('small')&&(document.querySelector('#return-date').parentElement.querySelector('small').textContent=copy.return);document.querySelector('.traveller-trigger')?.previousElementSibling&&(document.querySelector('.traveller-trigger').previousElementSibling.textContent=copy.passengers);document.querySelectorAll('.trip-types label:not(.direct-choice)').forEach((label,index)=>label.lastChild.textContent=[' '+copy.oneWay,' '+copy.roundTrip,' '+copy.multiCity][index]);document.querySelector('[data-runtime="direct"]')&&(document.querySelector('[data-runtime="direct"]').textContent=copy.direct);document.querySelector('[data-runtime="bookingClass"]')&&(document.querySelector('[data-runtime="bookingClass"]').textContent=copy.bookingClass)};refreshDynamicLocale();document.querySelector('#language')?.addEventListener('change',()=>setTimeout(refreshDynamicLocale));document.addEventListener('jtm-i18n-ready',refreshDynamicLocale);
const refreshPassengerCopy=()=>{const copy=runtimeCopy();const values=['adults','children','infants'].map(key=>Number(document.querySelector(`[data-count="${key}"]`)?.textContent||0));const trigger=document.querySelector('.traveller-trigger');if(trigger)trigger.textContent=[values[0]&&`${values[0]} ${copy.adult}`,values[1]&&`${values[1]} ${copy.child}`,values[2]&&`${values[2]} ${copy.infant}`].filter(Boolean).join(', ');document.querySelectorAll('.traveller-row b').forEach((item,index)=>item.textContent=[copy.adult,copy.child,copy.infant][index])};refreshPassengerCopy();document.querySelector('#language')?.addEventListener('change',()=>setTimeout(refreshPassengerCopy));document.addEventListener('jtm-i18n-ready',refreshPassengerCopy);
setTimeout(()=>{const form=document.querySelector('#multi-city-form');if(!form)return;const airports=['Jakarta (CGK)','Denpasar (DPS)','Surabaya (SUB)','Yogyakarta (YIA)','Medan (KNO)','Singapore (SIN)','Kuala Lumpur (KUL)','Bangkok (BKK)','Tokyo (NRT)','Seoul (ICN)'];const list=document.createElement('datalist');list.id='multi-city-airports';list.innerHTML=airports.map(airport=>`<option value="${airport}">`).join('');document.body.appendChild(list);const decorate=()=>form.querySelectorAll('.route-row input:not([type="date"])').forEach(input=>{input.setAttribute('list','multi-city-airports');input.setAttribute('autocomplete','off')});decorate();new MutationObserver(decorate).observe(form,{childList:true,subtree:true})},0);
