(() => {
  const form=document.querySelector('#turkey-visa-form');if(!form)return;
  const speed=document.querySelector('#turkey-speed'),quantity=document.querySelector('#turkey-quantity'),price=document.querySelector('#turkey-price'),total=document.querySelector('#turkey-total'),note=document.querySelector('#turkey-speed-note'),docs=document.querySelector('#turkey-documents'),feedback=document.querySelector('#turkey-feedback');
  const prices={normal:1500000,express:2000000,'super-express':2500000},money=value=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value);
  const renderDocs=()=>{const count=Math.min(10,Math.max(1,Number(quantity.value)||1));docs.innerHTML=Array.from({length:count},(_,index)=>`<div class="visa-upload"><b>Pemohon ${index+1}</b><small>Paspor dan foto wajib. PDF/JPG/PNG, maks. 5 MB per berkas.</small><label>Halaman biodata paspor<input name="passport_${index+1}" type="file" accept=".pdf,.jpg,.jpeg,.png" required></label><label>Foto diri<input name="face_${index+1}" type="file" accept=".jpg,.jpeg,.png" required></label><label>Tiket/hotel (opsional)<input name="support_${index+1}" type="file" accept=".pdf,.jpg,.jpeg,.png"></label></div>`).join('')};
  const refresh=()=>{const unit=prices[speed.value]||prices.normal;price.textContent=money(unit);total.textContent=money(unit*Math.min(10,Math.max(1,Number(quantity.value)||1)));note.textContent=speed.options[speed.selectedIndex].text};
  [speed,quantity].forEach(control=>control.addEventListener('input',()=>{refresh();renderDocs()}));form.querySelector('[name="phone"]').addEventListener('input',event=>event.target.value=event.target.value.replace(/\D/g,''));refresh();renderDocs();
  form.addEventListener('submit',async event=>{event.preventDefault();const data=new FormData(form);data.append('country','TR');data.append('visaType','turkey-single-30');data.append('processingSpeed',speed.value);data.append('quantity',quantity.value);feedback.textContent='Mengirim aplikasi…';try{const response=await fetch('/api/visa/create.php',{method:'POST',body:data}),result=await response.json();if(!response.ok||!result.ok)throw new Error(result.message||'Tidak dapat mengirim aplikasi.');feedback.textContent='Aplikasi diterima.';if(result.paymentUrl)location.href=result.paymentUrl}catch(error){feedback.textContent=error.message||'Koneksi pembayaran belum tersedia. Silakan hubungi tim kami.'}});
})();
