<?php
declare(strict_types=1);
$storage=getenv('JTM_VISA_STORAGE'); $token=getenv('JTM_VISA_ADMIN_TOKEN'); session_start();
if (!$storage || !$token) { http_response_code(503); exit('Visa admin is not configured.'); }
if (isset($_POST['login_token']) && hash_equals($token,(string)$_POST['login_token'])) { $_SESSION['jtm_visa_admin']=true; header('Location: /visa/admin/'); exit; }
if (empty($_SESSION['jtm_visa_admin'])) { exit('<!doctype html><title>JTM Visa Admin</title><form method="post" style="max-width:360px;margin:80px auto;font-family:system-ui"><h1>JTM Visa Admin</h1><label>Admin token<input name="login_token" type="password" required style="display:block;width:100%;margin:8px 0 14px;padding:10px"></label><button>Sign in</button></form>'); }
if ($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['case'],$_POST['status'])) { $file=rtrim($storage,DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR.basename($_POST['case']).DIRECTORY_SEPARATOR.'application.json'; $item=json_decode((string)@file_get_contents($file),true); $allowed=['SUBMITTED','PAID','IN REVIEW','APPROVED','REJECTED']; if ($item && in_array($_POST['status'],$allowed,true)) { $item['status']=$_POST['status']; $item['updatedAt']=gmdate('c'); file_put_contents($file,json_encode($item,JSON_PRETTY_PRINT),LOCK_EX); @mail($item['email'],'Jasa Tiket Murah — visa status '.$item['status'],"<p>Case <b>{$item['caseNumber']}</b> is now <b>{$item['status']}</b>.</p>","MIME-Version: 1.0\r\nContent-Type: text/html; charset=UTF-8\r\nFrom: noreply@jasatiketmurah.com\r\nCc: cs@jasatiketmurah.com\r\nBcc: jasatiketmurah@gmail.com"); } }
$rows=[]; foreach (glob(rtrim($storage,DIRECTORY_SEPARATOR).'/*/application.json')?:[] as $file) $rows[]=json_decode((string)file_get_contents($file),true); usort($rows,fn($a,$b)=>strcmp($b['createdAt'],$a['createdAt']));
?><!doctype html><meta charset="utf-8"><title>JTM Visa Admin</title><style>body{font:14px system-ui;margin:32px;color:#0d1b2a}table{border-collapse:collapse;width:100%}td,th{border:1px solid #dbe3ec;padding:10px;text-align:left}select,button{padding:7px}code{font-weight:700}</style><h1>JTM Visa Admin</h1><table><tr><th>Case</th><th>Status</th><th>Applicant</th><th>Visa</th><th>Total</th><th>Action</th></tr><?php foreach($rows as $row): ?><tr><td><code><?=htmlspecialchars($row['caseNumber'])?></code></td><td><?=htmlspecialchars($row['status'])?></td><td><?=htmlspecialchars($row['name'])?><br><?=htmlspecialchars($row['email'])?></td><td><?=htmlspecialchars($row['visaType'])?></td><td>Rp<?=number_format((int)$row['totalIDR'],0,',','.')?></td><td><form method="post"><input type="hidden" name="case" value="<?=htmlspecialchars($row['caseNumber'])?>"><select name="status"><?php foreach(['SUBMITTED','PAID','IN REVIEW','APPROVED','REJECTED'] as $s): ?><option <?=$s===$row['status']?'selected':''?>><?=$s?></option><?php endforeach?></select> <button>Update</button></form></td></tr><?php endforeach?></table>
